#!/bin/sh
###########################################################
# Copyright (C) 2001-2009, CompHEP Collaboration
# Author: Alexander Sherstnev 
###########################################################
export LHAPDF_DATA_PATH=
export COMPHEP=

if (test -f .compheppath) then
  export COMPHEP=`cat .compheppath`
else if (test -f ../.compheppath) then
  export COMPHEP=`cat ../.compheppath`
else if (test -f ../../.compheppath) then
  export COMPHEP=`cat ../../.compheppath`
else
  echo "\nn_comphep (warning): no .compheppath found in ./ or ../ or ../../. n_comphep.exe may function unproperly\n"
fi
fi
fi

if (test ! -d $COMPHEP) then
  echo " "
  echo "n_comphep (warning): no installed CompHEP in $COMPHEP"
  echo "      If you use the standard CompHEP installation, check .compheppath"
  echo "      If you use !-click installation, execute make relocate"
fi

if (test -f ../.lhapdfpath) then
  export LHAPDF_DATA_PATH=`cat ../.lhapdfpath`
  echo "\nn_comphep (info): LHAPDF is in use from $LHAPDF_DATA_PATH"
else if (test -f ../../.lhapdfpath) then
  export LHAPDF_DATA_PATH=`cat ../../.lhapdfpath`
  echo "\nn_comphep (info): LHAPDF is in use from $LHAPDF_DATA_PATH"
fi
fi

if (test -x n_comphep.exe) then
  if [ x$1 = xDEBUG ]; then
    (export COMPHEP=$COMPHEP;export LHAPDF_DATA_PATH=$LHAPDF_DATA_PATH;ddd n_comphep.exe $2 $3)
  else
    ./n_comphep.exe $1 $2
  fi
else
  echo "\nn_comphep (error): no file n_comphep.exe\n"
  exit
fi
