#!/bin/sh
###########################################################
# Copyright (C) 2008-2009, CompHEP Collaboration
# Author: Alexander Sherstnev 
###########################################################
#export COMPHEP=`cat .compheppath`
#export ROOTSYS=`cat .rootpath`
program=rtupler.exe
script=rtupler.sh

if (test -f .compheppath) then
  export COMPHEP=`cat .compheppath`
else if (test -f ../.compheppath) then
  export COMPHEP=`cat ../.compheppath`
else
  echo "\n  $script (error): .compheppath is not found in ./ or ../. $program can't function\n"
  exit
fi
fi

if (test -f .rootpath) then
  export ROOTSYS=`cat .rootpath`
else if (test -f ../.rootpath) then
  export ROOTSYS=`cat .rootpath`
else
  echo "\n  $script (error): .rootpath is not found in ./ or ../. $program can't function\n"
  exit
fi
fi
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH

LHAPDFPATH=
if (test -f ../.lhapdfpath) then
  export LHAPDFPATH=`cat ../.lhapdfpath`
  echo "\n  $script (info): LHAPDF is used from $LHAPDFPATH"
else if (test -f ../../.lhapdfpath) then
  export LHAPDFPATH=`cat ../../.lhapdfpath`
  echo "\n  $script (info): LHAPDF is used from $LHAPDFPATH"
fi
fi
export LD_LIBRARY_PATH=$LHAPDFPATH/lib:$LD_LIBRARY_PATH

if (test -z $1) then
   echo "***********************************************"
   echo "* INPUT ERROR: no input parameters            *"
   echo "* execute:                                    *"
   echo "*     ./$script --help                        *"
   echo "***********************************************"
   exit
fi

if (test -x $COMPHEP/bin/$program) then
  if [ x$1 = xDEBUG ]; then
    ddd $COMPHEP/bin/$program
  else
    $COMPHEP/bin/$program $*
  fi
else
  echo "\n  $script (error): no file $COMPHEP/bin/$program. Compile CompHEP in $COMPHEP\n"
  exit
fi
