#!/bin/sh
###########################################################
# Copyright (C) 2001-2009, CompHEP Collaboration
# Author: Alexander Sherstnev 
###########################################################
#export COMPHEP=`cat .compheppath`
script=unweighter.sh
program=unweighter.exe

if (test -f .compheppath) then
  export COMPHEP=`cat .compheppath`
else if (test -f ../.compheppath) then
  export COMPHEP=`cat ../.compheppath`
else
  echo "\n  $script (error): .compheppath is not found in ./ or ../. $program can't function\n"
  exit
fi
fi

if (test -z $1) then
   echo "***********************************************"
   echo "* INPUT ERROR: no input parameters            *"
   echo "* execute:                                    *"
   echo "*     ./$script --help                        *"
   echo "***********************************************"
   exit
fi

export ROOTSYS=`cat .rootpath`
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH

if (test -x $COMPHEP/bin/$program) then
  if [ x$1 = xDEBUG ]; then
    ddd $COMPHEP/bin/$program
  else
    $COMPHEP/bin/$program $*
  fi
else
  echo "\n  $script (error): no file $COMPHEP/bin/$program. Compile CompHEP in $COMPHEP\n"
  exit
fi
