####################################################
# Copyright (C) 2001-2009, CompHEP Collaboration   #
# Author: A. Sherstnev                             #
####################################################
doc:
#	${MAKE} -C manual

clean:
#	${MAKE} -C manual clean
